name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/deps

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.0

      - name: Vet
        run: source activate-opt && go vet ./...

      - name: Build
        run: source activate-opt && go build -v ./cmd/radiance
